### ISSUE TITLE
Plagiarized docs

### ISSUE THREAD

**Issue by Sammyjo20** [jenky/atlas#21]
Hey @jenky 

I noticed that this library has plagiarised a lot of my documentation from my library, Saloon: https://docs.saloon.dev/

The introduction of your documentation is almost exactly the same as my documentation from a few versions ago

<img width="906" alt="Screenshot 2023-11-27 at 14 42 46" src="https://github.com/phanxipang/fansipan/assets/29132017/b70cec7d-e26f-4722-9f4a-6a736a4d6952">

Saloon's Docs:

<img width="856" alt="Screenshot 2023-11-27 at 14 43 33" src="https://github.com/phanxipang/fansipan/assets/29132017/f4a5cae7-f10b-44d6-942d-c4ef830eb771">

I also noticed quite a few other pages have been simply copied and not re-written.

I'm flattered that people are writing similar libraries to Saloon, but I'm not cool with people copying the writing that I spent a lot of time on.

**Comment by Sammyjo20** [comment]
Also, to be clear - I think your implementation is cool - it's clear you have spent a lot of time on the codebase and made changes that reflect your opinions on things which is awesome, so nice work on the library. I am just worried this was someone blindly copying and pasting my work.

**Comment by jenky** [comment]
Thank you for sharing your opinion and feedback. Regarding the document, I will update it soon.

To be honest, I created this when your salon was in its early version 1. Although your concept was very cool, there were a few things that I wanted to do differently. After careful consideration, I realized that the APIs would be different, so I decided to create my own version. The main factors that influenced my decision were the monolith I am currently working on, which is still on PHP7 😂. Additionally, as the SDK developer, I believe it is reasonable to target a wider user base because upgrading a legacy codebase is a nightmare and requires significant effort to accomplish. Sometimes, from a business perspective, it doesn't matter as long as it works, so you just have to deal with it 🤷. Happy coding 🧑‍💻!

**Comment by Sammyjo20** [comment]
Thanks @jenky, and I apologise for my initial abruptness. Had a stressful day.

I was having a read through of your library and I really like some of the design decisions that you made. I hope this package is successful! 

Take care and happy coding too 🤠
